apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: argoCD
  region: us-east-1
  version: "1.34" 

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  cidr: "192.168.0.0/16"

managedNodeGroups:
  - name: standard-nodes
    instanceType: m7i-flex.large
    desiredCapacity: 2
    volumeSize: 30
    ssh:
      allow: true
      publicKeyName: jenkins

addons:
  - name: eks-pod-identity-agent
  - name: vpc-cni
    useDefaultPodIdentityAssociations: true
  - name: aws-ebs-csi-driver
    useDefaultPodIdentityAssociations: true
  - name: kube-proxy
  - name: coredns
