apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerapp-deployment
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: dockersamples/examplevotingapp_worker
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits: # Added for 2026 stability
            cpu: "500m"
            memory: "512Mi"
